# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  name: ServerCASA
  latitude: 45.464211
  longitude: 9.191383
  elevation: 140
  country: IT
  unit_system: metric
  time_zone: Europe/Rome
  packages: !include_dir_named integrations

system_health:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /hacsfiles/simple-thermostat/simple-thermostat.js

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
scene: !include scenes.yaml
      